services:
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jData:/data
  nats:
    image: nats
    ports:
      - "4222:4222"
volumes:
  neo4jData: {}
